# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-04 03:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='birthday',
            field=models.DateTimeField(verbose_name='birthday'),
        ),
    ]
